require('dotenv').config();

export class AtcNameService {
    private atcNames: { [key: string]: string } = {
        "RKSI_DEL": "Incheon Delivery",
        "RKSI_GND": "Incheon Ground",
        "RKSI_1_GND": "Incheon Apron",
        "RKSI_2_GND": "Incheon Apron",
        "RKSI_A_GND": "Incheon Apron",
        "RKSI_TWR": "Incheon Tower",
        "RKSI_W_TWR": "Incheon Tower",
        "RKSS_DEL": "Gimpo Delivery",
        "RKSS_GND": "Gimpo Ground",
        "RKSS_A_GND": "Gimpo Apron",
        "RKSS_TWR": "Gimpo Tower",
        "RKPC_DEL": "Jeju Delivery",
        "RKPC_GND": "Jeju Ground",
        "RKPC_TWR": "Jeju Tower",
        "RKPK_DEL": "Gimhae Delivery",
        "RKPK_GND": "Gimhae Ground",
        "RKPK_A_GND": "Gimhae Apron",
        "RKPK_TWR": "Gimhae Tower",
        "RKTU_DEL": "Cheongju Delivery",
        "RKTU_GND": "Cheongju Ground",
        "RKTU_TWR": "Cheongju Tower",
        "RKNY_DEL": "YangYang Delivery",
        "RKNY_GND": "YangYang Ground",
        "RKNY_TWR": "YangYang Tower",
        "RKTN_DEL": "Deagu Delivery",
        "RKTN_GND": "Deagu Ground",
        "RKTN_TWR": "Deagu Tower",
        "RKJJ_DEL": "Gwangju Delivery",
        "RKJJ_GND": "Gwangju Ground",
        "RKJJ_TWR": "Gwangju Tower",
        "RKJK_DEL": "Gunsan Delivery",
        "RKJK_GND": "Gunsan Ground",
        "RKJK_TWR": "Gunsan Tower",
        "RKJY_DEL": "Yeosu Delivery",
        "RKJY_GND": "Yeosu Ground",
        "RKJY_TWR": "Yeosu Tower",
        "RKNW_DEL": "Wonju Delivery",
        "RKNW_GND": "Wonju Ground",
        "RKNW_TWR": "Wonju Tower",
        "RKPS_DEL": "Sacheon Delivery",
        "RKPS_GND": "Sacheon Ground",
        "RKPS_TWR": "Sacheon Tower",
        "RKSM_DEL": "Seoul Delivery",
        "RKSM_GND": "Seoul Ground",
        "RKSM_TWR": "Seoul Tower",
        "RKTH_DEL": "Pohang Delivery",
        "RKTH_GND": "Pohang Ground",
        "RKTH_TWR": "Pohang Tower",
        "RKPD_DEL": "Jeongseok Delivery",
        "RKPD_GND": "Jeongseok Ground",
        "RKPD_TWR": "Jeongseok Tower",
        "RKJB_DEL": "Muan Delivery",
        "RKJB_GND": "Muan Ground",
        "RKJB_TWR": "Muan Tower",
        "RKTL_DEL": "Uljin Delivery",
        "RKTL_GND": "Uljin Ground",
        "RKTL_TWR": "Uljin Tower",
        "RKSS_APP": "Seoul Approach",
        "RKSS_DEP": "Seoul Departure",
        "RKSI_A_APP": "Incheon Arrival",
        "RKSS_A_APP": "Gimpo Arrival",
        "RKPC_APP": "Jeju Approach",
        "RKPC_DEP": "Jeju Departure",
        "RKPK_APP": "Gimhae Approach",
        "RKPK_DEP": "Gimhae Arrival",
        "RKDA_CTR": "Deagu Control",
        "RKRR_CTR": "Incheon Control",
        "RKRR_A_CTR": "Incheon Control"
    };

    public getAtcName(option: string): string {
        return this.atcNames[option] || "Unknown ATC";
    }
}